# Generated by Django 2.1.7 on 2019-03-26 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 17, 6, 8, 238286, tzinfo=utc)),
        ),
    ]
