# Generated by Django 2.1.7 on 2019-03-26 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190326_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 17, 7, 1, 767307, tzinfo=utc)),
        ),
    ]
