# Generated by Django 2.1.7 on 2019-03-26 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190326_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 17, 9, 3, 796557, tzinfo=utc)),
        ),
    ]
