# Generated by Django 2.1.7 on 2019-03-26 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 17, 6, 8, 241239, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='num_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='num_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 17, 6, 8, 241239, tzinfo=utc)),
        ),
    ]
