# Generated by Django 2.1.7 on 2019-03-26 17:06

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20190326_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 17, 6, 43, 739124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
