# Generated by Django 2.1.7 on 2019-03-26 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20190326_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
